name: flashcard_app
description: English-Korean Flashcard Learning App
version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^6.1.6
  googleapis: ^11.4.0
  googleapis_auth: ^1.4.1
  http: ^1.1.0
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  confetti: ^0.7.0
  flutter_secure_storage: ^9.0.0
  connectivity_plus: ^5.0.2
  sqflite: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true 