spring:
  application:
    name: kotlin-in-depth-book

  datasource:
    url: jdbc:h2:mem:testdb  # ???? H2 ?????? ??
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect  # H2 Dialect ??
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true  # H2 ?? ???
      path: /h2-console

